// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISetSystem {
  function set(uint32 index, uint32 x, uint32 y, uint8 value) external;
}
